RelativeURLs=true
CanonifyURLs=true
languageCode = "ko-KR"
defaultContentLanguage = "ko"
showHeaderLanguageChooser=true
defaultContentLanguageInSubdir= true
# googleAnalytics = "UA-161422664-1"

title = "General Immersion Day Workshop"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  editURL = "https://code.amazon.com/packages/Aws-workshop-template/blobs/master/--/workshop/content/"
  description = "General Immersion Day Workshop"
  author = "joozero"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> AWS Homepage"
  url = "https://aws.amazon.com/"
  weight = 1000

[[menu.shortcuts]]
  name = "<i class='fas fa-blog'></i> AWS Blog"
  url = "https://aws.amazon.com/blogs/aws/"
  weight = 1020

[[menu.shortcuts]]
  name = "<i class='fab fa-facebook-square'></i> Facebook"
  url = "https://www.facebook.com/groups/awskrug/"
  weight = 1030

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Languages]
  [Languages.ko]
    weight = 1
    languageName = "한국어"

  [Languages.en]
    weight = 2
    languageName = "English"
  
  [Languages.pt]
    weight = 3
    languageName = "Portuguese"
